submit:
	mkdir submit
	cp RSP_paper_new.tex submit/
	cp RSP_library.bib submit/
	cp RSP_paper_new.bbl submit/
	cp HISTOGRAMS.pdf                             submit/
	cp MAIN_color_results_with_spline_no_mc_1.pdf submit/
	cp MAIN_color_results_with_spline_no_mc_2.pdf submit/
	cp MAIN_results_with_spline_no_mc_1.pdf submit/
	cp MAIN_results_with_spline_no_mc_2.pdf submit/
	cp Planck_summary.pdf submit/
	cp color_vs_z.pdf submit/
	cp skymaps.pdf submit/
	cp corner215.pdf submit/
