submit:
	mkdir submit
	cp Planck_summary.pdf submit/
	cp 2D_graphs_with_spline_no_mc.pdf  submit/
	cp 3D_graphs_with_spline_no_mc.pdf submit/
	cp derivatives_with_spline_no_mc.pdf submit/
	cp splashback_with_spline_no_mc.pdf submit/
	cp color_separated_2D_with_spline_no_mc.pdf submit/
	cp color_separated_3D_with_spline_no_mc.pdf submit/
	cp corner21.pdf submit/
	cp corner215.pdf submit/
	cp corner22.pdf submit/
	cp cornerred.pdf submit/
	cp cornerblue.pdf submit/
	cp color_vs_z.pdf submit/
	cp mag_errors.png submit/
	cp Planck_pres.png submit/
	cp heal_maps.png submit/
	cp RSP_paper_new.tex submit/
	cp RSP_library.bib submit/
	cp RSP_paper_new.bbl submit/
